"""New public reference: deterministic tiny EPUB + generated tone, no AI calls.

The fixture is deliberately synthetic. This is not the private EPUB exporter
and it is not an audiobook generated by Morgenstern.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import struct
import wave
import zipfile
from pathlib import Path
from media_gate import probe_media

FILES = {
    "mimetype": "application/epub+zip",
    "META-INF/container.xml": '<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="EPUB/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>',
    "EPUB/package.opf": '<?xml version="1.0"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="id">urn:example:morgenstern-public-fixture</dc:identifier><dc:title>La máquina también revisa</dc:title><dc:language>es</dc:language><dc:creator>Calin Rus</dc:creator><meta property="dcterms:modified">2026-09-28T00:00:00Z</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="chapter" href="chapter.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="chapter"/></spine></package>',
    "EPUB/nav.xhtml": '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="es" xml:lang="es"><head><title>Índice</title></head><body><nav epub:type="toc"><h1>Índice</h1><ol><li><a href="chapter.xhtml">Una entrega pequeña</a></li></ol></nav></body></html>',
    "EPUB/chapter.xhtml": '<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head><title>Una entrega pequeña</title></head><body><h1>Una entrega pequeña</h1><p>Generar un archivo es fácil. Saber qué contiene ya exige trabajo.</p><p>Esta muestra es sintética. Sirve para inspeccionar estructura, hashes y validación sin manuscritos privados ni servicios externos.</p></body></html>',
}


def make_epub(path: Path) -> None:
    with zipfile.ZipFile(path, "w") as archive:
        for name, text in FILES.items():
            entry = zipfile.ZipInfo(name, date_time=(2026, 9, 28, 0, 0, 0))
            # ZipInfo otherwise embeds the host OS (Windows vs Unix).
            # Fix both origin and mode so identical input has identical bytes.
            entry.create_system = 3
            entry.external_attr = 0o100644 << 16
            entry.compress_type = zipfile.ZIP_STORED
            archive.writestr(entry, text.encode("utf-8"))


def make_tone(path: Path) -> None:
    with wave.open(str(path), "wb") as audio:
        audio.setnchannels(1)
        audio.setsampwidth(2)
        audio.setframerate(16000)
        audio.writeframes(b"".join(struct.pack("<h", round(1800 * math.sin(2 * math.pi * 440 * i / 16000))) for i in range(16000)))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("build/public-demo"))
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    book, tone = args.output / "sample.epub", args.output / "tone.wav"
    make_epub(book)
    make_tone(tone)
    report = {"fixture": "synthetic; no AI generation", "audio": probe_media(tone, "audio", .9),
              "sha256": {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in [book, tone]}}
    (args.output / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
